# These are supported funding model platforms

github: [dev-rashedin]
patreon: 
open_collective: express-error-toolkit
ko_fi: dev_rashedin
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
lfx_crowdfunding: 
polar: 
buy_me_a_coffee: 
thanks_dev: 
custom:
